language: rust
cache: cargo
sudo: false
os:
- linux
- osx
rust:
- nightly
- beta
- stable
script:
- cargo test
branches:
  only:
    master
install:
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew reinstall -s libtool; fi
matrix:
  allow_failures:
    - rust: nightly
