language: rust
sudo: false
script:
- cargo test
- cargo doc --no-deps -p c-ares
branches:
  only:
    master
install:
- pip install ghp-import --user $USER
after_success: |
  [ $TRAVIS_PULL_REQUEST = false ] && bash ./publish-docs.sh
