language: rust
cache: cargo
sudo: false
os:
- linux
- osx
rust:
- nightly
- beta
- stable
script:
- cargo test
- if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then cargo update -Z minimal-versions; fi
- if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then cargo build; fi
branches:
  only:
    master
install:
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew reinstall -s libtool; fi
matrix:
  allow_failures:
    - rust: nightly
