image: Visual Studio 2017
branches:
    only:
      - master
environment:
  matrix:
  - target: x86_64-pc-windows-msvc
    VCVARS: '"c:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"'
    channel: stable
  - target: i686-pc-windows-msvc
    VCVARS: '"c:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"'
    channel: stable
  - target: x86_64-pc-windows-msvc
    VCVARS: '"c:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"'
    channel: beta
  - target: i686-pc-windows-msvc
    VCVARS: '"c:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"'
    channel: beta
  - target: x86_64-pc-windows-msvc
    VCVARS: '"c:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"'
    channel: nightly
  - target: i686-pc-windows-msvc
    VCVARS: '"c:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"'
    channel: nightly
matrix:
  allow_failures:
  - channel: nightly
install:
  - ps: .\install-rust.ps1
  - call %VCVARS%
  - git submodule init
  - git submodule update

build: false

test_script:
  - cargo test
