[package]
name = "c-ares"
license = "MIT"
version = "0.19.0"
authors = ["David Hotham"]
description = """
A Rust wrapper for the c-ares library, for asynchronous DNS requests.
"""
homepage = "https://github.com/dimbleby/rust-c-ares"
repository = "https://github.com/dimbleby/rust-c-ares"
documentation = "http://dimbleby.github.io/rust-c-ares"
readme = "README.md"
keywords = ["DNS", "c-ares"]

[dependencies]
c-ares-sys = { version = "0.11.0", path = "c-ares-sys" }
bitflags = "0.4.0"
c-types = "*"

[target.'cfg(unix)'.dev-dependencies]
mio = "*"
nix = "*"

[target.'cfg(windows)'.dev-dependencies]
winapi = "*"
ws2_32-sys = "*"
