[package]
name = "c-ares"
license = "MIT"
version = "0.22.0"
authors = ["David Hotham"]
description = """
A Rust wrapper for the c-ares library, for asynchronous DNS requests.
"""
homepage = "https://github.com/dimbleby/rust-c-ares"
repository = "https://github.com/dimbleby/rust-c-ares"
documentation = "http://dimbleby.github.io/rust-c-ares"
readme = "README.md"
keywords = ["DNS", "c-ares"]

[dependencies]
bitflags = "0.7"
c-ares-sys = { version = "1.0", path = "c-ares-sys" }
c-types = "0.1"
itertools = "0.5"

[target.'cfg(unix)'.dev-dependencies]
futures = "0.1"
mio = "0.6"
nix = "0.7"
tokio-core = "0.1"

[target.'cfg(windows)'.dev-dependencies]
winapi = "0.2"
ws2_32-sys = "0.2"
