[package]
name = "c-ares"
license = "MIT"
version = "0.15.0"
authors = ["David Hotham"]
description = """
A Rust wrapper for the c-ares library, for asynchronous DNS requests.
"""
homepage = "https://github.com/dimbleby/rust-c-ares"
repository = "https://github.com/dimbleby/rust-c-ares"
documentation = "http://dimbleby.github.io/rust-c-ares"
readme = "README.md"
keywords = ["DNS", "c-ares"]

[dependencies]
libc = "0.1.12"
bitflags = "*"
winapi = "*"

[dependencies.c-ares-sys]
path = "c-ares-sys"

[dev-dependencies]
mio = { git = "https://github.com/dimbleby/mio", branch = "use-time-not-clock-ticks" }
nix = "*"
ws2_32-sys = "*"
