[package]
name = "c-ares"
license = "MIT"
version = "2.1.0"
authors = ["David Hotham"]
description = """
A Rust wrapper for the c-ares library, for asynchronous DNS requests.
"""
repository = "https://github.com/dimbleby/rust-c-ares"
documentation = "http://dimbleby.github.io/rust-c-ares"
readme = "README.md"
keywords = ["DNS", "c-ares"]
categories = ["api-bindings", "asynchronous", "network-programming"]

[dependencies]
bitflags = "0.9"
c-ares-sys = { version = "3", path = "c-ares-sys" }
c-types = "1"
itertools = "0.6"

[target.'cfg(unix)'.dev-dependencies]
futures = "0.1"
mio = "0.6"
mio-more = "0.1"
nix = "0.8"
tokio-core = "0.1"

[target.'cfg(windows)'.dev-dependencies]
winapi = "0.2"
ws2_32-sys = "0.2"

[workspace]
