[package]
name = "c-ares"
license = "MIT"
version = "0.3.0"
authors = ["David Hotham"]
description = "A Rust wrapper for the c-ares library"
homepage = "https://github.com/dimbleby/rust-c-ares"
repository = "https://github.com/dimbleby/rust-c-ares"
documentation = "http://dimbleby.github.io/rust-c-ares"
readme = "README.md"
keywords = ["DNS", "c-ares"]

[dependencies]
libc = "0.1.0"
bitflags = "0.3.0"
c-ares-sys = "0.1.0"
mio = "0.4.0"
