[package]
name = "c-ares"
license = "MIT"
version = "5.0.0"
authors = ["David Hotham"]
description = """
A Rust wrapper for the c-ares library, for asynchronous DNS requests.
"""
repository = "https://github.com/dimbleby/rust-c-ares"
documentation = "http://dimbleby.github.io/rust-c-ares"
readme = "README.md"
keywords = ["DNS", "c-ares"]
categories = ["api-bindings", "asynchronous", "network-programming"]

[dependencies]
bitflags = "1"
c-ares-sys = { version = "4", path = "c-ares-sys" }
c-types = "2"
itertools = "0.7"

[target.'cfg(unix)'.dev-dependencies]
futures = "0.1"
mio = "0.6"
mio-extras = "1"
nix = "0.9"
tokio-core = "0.1"

[target.'cfg(windows)'.dev-dependencies]
winapi = { version = "0.3", features = ["winsock2"] }

[workspace]
