[package]
name = "c-ares"
license = "MIT"
version = "0.17.0"
authors = ["David Hotham"]
description = """
A Rust wrapper for the c-ares library, for asynchronous DNS requests.
"""
homepage = "https://github.com/dimbleby/rust-c-ares"
repository = "https://github.com/dimbleby/rust-c-ares"
documentation = "http://dimbleby.github.io/rust-c-ares"
readme = "README.md"
keywords = ["DNS", "c-ares"]

[dependencies]
bitflags = "*"
c-types = "*"
ip = "*"

[dependencies.c-ares-sys]
path = "c-ares-sys"

[dev-dependencies]
mio = "*"
nix = "*"
winapi = "*"
ws2_32-sys = "*"
