[package]
name = "c-ares"
license = "MIT"
version = "0.13.0"
authors = ["David Hotham"]
description = """
A Rust wrapper for the c-ares library, for asynchronous DNS requests.
"""
homepage = "https://github.com/dimbleby/rust-c-ares"
repository = "https://github.com/dimbleby/rust-c-ares"
documentation = "http://dimbleby.github.io/rust-c-ares"
readme = "README.md"
keywords = ["DNS", "c-ares"]

[dependencies]
c-ares-sys = "0.4.0"
libc = "0.1.10"
bitflags = "0.3.2"

[dev-dependencies]
mio = "0.4.2"
nix = "0.3.9"
