[package]
name = "c-ares"
license = "MIT"
version = "0.18.0"
authors = ["David Hotham"]
description = """
A Rust wrapper for the c-ares library, for asynchronous DNS requests.
"""
homepage = "https://github.com/dimbleby/rust-c-ares"
repository = "https://github.com/dimbleby/rust-c-ares"
documentation = "http://dimbleby.github.io/rust-c-ares"
readme = "README.md"
keywords = ["DNS", "c-ares"]

[dependencies]
c-ares-sys = "0.10.0"
bitflags = "0.3.3"
c-types = "0.1.3"

[dev-dependencies]
mio = "0.5.0"
nix = "0.5.0"
winapi = "0.2.5"
ws2_32-sys = "0.2.1"
