[package]
name = "c-ares"
license = "MIT"
version = "0.1.0"
authors = ["David Hotham"]
description = "A Rust wrapper for the c-ares library"
homepage = "https://github.com/dimbleby/rust-c-ares"
readme = "README.md"
keywords = ["DNS", "c-ares"]

[dependencies]
libc = "*"
c-ares-sys = "0.1.0"

[dev-dependencies]
mio = "0.4.0"
