[package]
name = "c-ares-sys"
license = "MIT"
version = "0.14.0"
authors = ["David Hotham"]
build = "build.rs"
links = "cares"
description = "Low-level bindings to the c-ares library"
homepage = "https://github.com/dimbleby/rust-c-ares"
repository = "https://github.com/dimbleby/rust-c-ares"
readme = "README.md"
keywords = ["DNS", "c-ares"]

[build-dependencies]
gcc = "0.3.38"
pkg-config = "0.3.8"

[dependencies]
libc = "0.2.17"
c-types = "0.1.4"

[target.'cfg(windows)'.dependencies]
winapi = "0.2.8"
