[package]
name = "c-ares-sys"
license = "MIT"
version = "0.11.0"
authors = ["David Hotham"]
links = "cares"
build = "build.rs"
description = "Low-level bindings to the c-ares library"
homepage = "https://github.com/dimbleby/rust-c-ares"
repository = "https://github.com/dimbleby/rust-c-ares"
readme = "README.md"
keywords = ["DNS", "c-ares"]

[build-dependencies]
gcc = "*"
pkg-config = "*"

[dependencies]
libc = "*"
c-types = "*"
winapi = "*"
