[package]
name = "c-ares-sys"
license = "MIT"
version = "1.0.1"
authors = ["David Hotham"]
build = "build.rs"
links = "cares"
description = "Low-level bindings to the c-ares library"
homepage = "https://github.com/dimbleby/rust-c-ares"
repository = "https://github.com/dimbleby/rust-c-ares"
readme = "README.md"
keywords = ["DNS", "c-ares"]
categories = ["external-ffi-bindings", "network-programming"]

[build-dependencies]
gcc = "0.3"
metadeps = "1"

[dependencies]
libc = "0.2"
c-types = "1"

[target.'cfg(windows)'.dependencies]
winapi = "0.2"

[package.metadata.pkg-config]
libcares = "1.12.0"
