[package]
name = "c-ares-sys"
license = "MIT"
version = "0.1.1"
authors = ["David Hotham"]
description = "Low-level bindings to the c-ares library"
homepage = "https://github.com/dimbleby/rust-c-ares"
repository = "https://github.com/dimbleby/rust-c-ares"
readme = "README.md"
keywords = ["DNS", "c-ares"]

[dependencies]
libc = "*"
