[package]
name = "c-ares-sys"
license = "MIT"
version = "0.6.0"
authors = ["David Hotham"]
links = "cares"
build = "build.rs"
description = "Low-level bindings to the c-ares library"
homepage = "https://github.com/dimbleby/rust-c-ares"
repository = "https://github.com/dimbleby/rust-c-ares"
readme = "README.md"
keywords = ["DNS", "c-ares"]

[build-dependencies]
gcc = "0.3.20"
pkg-config = "0.3.6"

[dependencies]
libc = "0.2.2"
c-types = "0.1.2"
winapi = "0.2.5"
